# -*- mode: ruby -*-
# vi: set ft=ruby :

machines = {
  'alma-8' => {'memory' => '1024', 'cpus' => 1, 'ip' => '22', 'box' => 'almalinux/8', 'provision' => 'alma.sh'},
}

specified_machines = ENV['MACHINES'].to_s.split(',')

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  machines.each do |name, conf|
    next unless specified_machines.empty? || specified_machines.include?(name)

    config.vm.define "#{name}" do |m|
      m.vm.box = "#{conf['box']}"
      m.vm.network 'private_network', ip: "192.168.57.#{conf['ip']}"
      m.vm.hostname = "#{name}"
      m.vm.provider 'libvirt' do |lv|
        lv.memory = conf['memory']
        lv.cpus = conf['cpus']
        lv.host = 'localhost'
        lv.driver = 'kvm'
        lv.uri = 'qemu:///system'
        #lv.connect_via_ssh = false
        lv.username = 'root'  # Replace with your username
      end
      m.vm.disk :disk, size: "25GB", name: "new_storage"
      m.vm.provision 'shell', path: "provision/#{conf['provision']}"
    end
  end
end
