name: clang-format check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.14.0
      with:
        clang-format-version: '19'
        check-path: 'src'

